### ISSUE TITLE
Błąd sprawdzania wersji Hełma

### ISSUE THREAD

**Issue by WojciechKarpiel** [kiemlicz/shelm#12]
`Helm` ściągnięty z Fedorowego repozytorium zwraca "v3.5" jako swoją wersję, przez co budowanie czortów wysypuje się:

```
[error] java.lang.RuntimeException: Cannot assert Helm version (must be at least 3.0.0): 3.5
[error]         at scala.sys.package$.error(package.scala:30)
[error]         at io.github.kiemlicz.shelm.HelmPlugin$autoImport$.$anonfun$baseHelmSettings$13(HelmPlugin.scala:64)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error]         at sbt.Execute.work(Execute.scala:291)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error]         at java.base/java.lang.Thread.run(Thread.java:829)
```
Problematyczny fragment (brak obsługi wersji w postaci `Seq(major, _)`):
```
        helmVer match {
          case VersionNumber(Seq(major, _, _), _, _) if major >= 3 =>
          case _ => sys.error(s"Cannot assert Helm version (must be at least 3.0.0): $helmVer")
        }
```

Pozostałe szczegóły:
```
$ helm version --template {{.Version}}
v3.5
$ dnf info helm
Ostatnio sprawdzono ważność metadanych: 0:01:37 temu w dniu czw, 17 lut 2022, 07:54:56.
Zainstalowane pakiety
Nazwa        : helm
Wersja       : 3.5.4
Wydanie      : 2.fc35
Architektura : x86_64
Rozmiar      : 46 M
Źródło       : golang-helm-3-3.5.4-2.fc35.src.rpm
Repozytorium : @System
Z repoz.     : fedora
Podsumowanie : The Kubernetes Package Manager
Adres URL    : https://github.com/helm/helm
Licencja     : ASL 2.0
Opis         : 
             : Helm is a tool for managing Charts. Charts are packages of pre-configured
             : Kubernetes resources.
             : 
             : Use Helm to:
             : - Find and use popular software packaged as Helm Charts to run in Kubernetes
             : - Share your own applications as Helm Charts
             : - Create reproducible builds of your Kubernetes applications
             : - Intelligently manage your Kubernetes manifest files
             : - Manage releases of Helm packages
```

**Comment by kiemlicz** [comment]
Naprawione od wersji 0.6.3

Please verify that `0.6.3` is working properly and re-open if issue persists

**Comment by WojciechKarpiel** [comment]
Dzięki, działa!
